print("apt install python3")
print("apt install figlet")
print("figlet D0RKLIS7")
print("Ferramenta listadora de dorks para google hacking")
print("Created by ANDR0MED4")
print()
print("[1] Dorks Sql-Map")
print("[2] Dorks Osint")
print("[3] Dorks Pesquisa Certeira")
opção = int(input("Qual a sua escolha meu nobre?"))
if opção == 1:
    print("view_items.php?id=")
    print("home.php?cat=")
    print("item_book.php?CAT=")
    print("www/index.php?page=")
    print("view_items.php?id=")
    print("customer/board.htm?mode=")
    print("help/com_view.html?code=")
    print("n_replyboard.php?typeboard=")
    voltar = int(input("Para apagar tudo digite 0"))
    if voltar == 0:
            print("clear")
    else:
        print("Comando desconhecido")
elif opção == 2:
    print("[encontrar email] nickdapessoa*com")
    print("Nome-Da-Pessoa filetype:pdf OR filetype:xlsx OR")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")